[project]
name = "codeboxapi"
version = "0.2.0"
description = "CodeBox gives you an easy scalable and isolated python interpreter for your LLM Agents."
keywords = [
    "codeboxapi",
    "code-interpreter",
    "codebox-api",
    "language model",
    "codeinterpreterapi",
]
authors = [{ name = "Shroominic", email = "contact@shroominic.com" }]
dependencies = [
    "pydantic>=2",
    "pydantic-settings>=2",
    "requests>=2",
    "aiohttp>=3.9",
]
readme = "README.md"
requires-python = ">= 3.9"
license = { text = "MIT" }

[project.urls]
repository = "https://github.com/shroominic/codebox-api"
api-reference = "https://codeboxapi.com/docs"
docs = "https://codeboxapi.com/docs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "codeboxapi[all]",
    "mypy>=1.8",
    "ruff>=0.1",
    "pytest>=7.4",
    "pre-commit>=3.5",
    "neoteroi-mkdocs>=1",
    "mkdocs-material>=9",
    "types-requests>=2.31",
    "matplotlib>=3.8.2",
    "jupyter-client>=8.6.0",
    "ipykernel>=6.29.3",
    "pip",
    "rich>=13.7.0",
]

[project.optional-dependencies]
local = ["jupyter-client", "ipykernel"]
image = ["Pillow"]
all = ["codeboxapi[local]", "codeboxapi[image]"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/codeboxapi"]

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E701"]

[tool.ruff.format]
preview = true
